### ISSUE TITLE
serial.serialutil.SerialException: Cannot configure port, something went wrong. Original message: PermissionError(13, 'The device connected to the system is not working.', None, 31)

### ISSUE THREAD

**Issue by fengyanWang** [dzhu/myo-raw#31]
Hello there!
The package you provided is very useful, but when I was using it recently, the serial port was always broken. The error message is as follows: 
**serial.serialutil.SerialException: Cannot configure port, something went wrong. Original message: PermissionError(13, 'The device connected to the system is not working.', None, 31)**
Those who hope to encounter similar problems can give a solution that has been debugged for a long time!
Thank you

**Comment by BczImHappy** [comment]
I also encountered the same problem when I run myo_raw.py

**Comment by fengyanWang** [comment]
I tried a lot of things, but they didn't work, and it turned out to be a problem with device sleep. However, according to the official command set never to sleep, the result is the same, as if the command did not set the success, do not know the specific problems and solutions

**Comment by mr-xuxu** [comment]
if self.ser.isOpen():
                pass
            else:
                try:
                    self.ser.open()
                except:
                    print("发生异常:")
                    print('traceback.format_exc():\n{}'.format(traceback.format_exc()))
                    print("关闭串口：")
                    self.ser.close()
                    print("打开串口：")
                    self.ser.open()
                    print("打开串口成功：")
                    print("继续执行程序")

**Comment by mr-xuxu** [comment]
发生异常:
traceback.format_exc():
Traceback (most recent call last):
  File "D:\xuxu\GPIB_ATUO\at_cmd.py", line 109, in write
    self.ser.open()
  File "C:\Python36-32\lib\site-packages\serial\serialwin32.py", line 78, in open
    self._reconfigure_port()
  File "C:\Python36-32\lib\site-packages\serial\serialwin32.py", line 222, in _reconfigure_port
    'Original message: {!r}'.format(ctypes.WinError()))
serial.serialutil.SerialException: Cannot configure port, something went wrong. Original message: PermissionError(13, '连到系统上的设备没有发挥作用。', None, 31)

**Comment by arthurross88** [comment]
Arduino:1.8.9 (Windows 10), Board:"LOLIN(WEMOS) D1 mini Lite, 80 MHz, Flash, Disabled, All SSL ciphers (most compatible), 1M (no SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

De schets gebruikt 386576 bytes (37%)  programma-opslagruimte. Maximum is 1023984 bytes.
Globale variabelen gebruiken 28684 bytes (35%) van het dynamisch geheugen. Resteren 53236 bytes voor lokale variabelen. Maximum is 81920 bytes.
esptool.py v2.6
2.6
esptool.py v2.6
Serial port COM8
Traceback (most recent call last):
  File "C:\Users\Arthur\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2/tools/upload.py", line 25, in <module>
    esptool.main(fakeargs)
  File "C:/Users/Arthur/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/tools/esptool\esptool.py", line 2652, in main
    esp = chip_class(each_port, initial_baud, args.trace)
  File "C:/Users/Arthur/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/tools/esptool\esptool.py", line 222, in __init__
    self._port = serial.serial_for_url(port)
  File "C:/Users/Arthur/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/tools/pyserial\serial\__init__.py", line 88, in serial_for_url
    instance.open()
  File "C:/Users/Arthur/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/tools/pyserial\serial\serialwin32.py", line 78, in open
    self._reconfigure_port()
  File "C:/Users/Arthur/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/tools/pyserial\serial\serialwin32.py", line 222, in _reconfigure_port
    'Original message: {!r}'.format(ctypes.WinError()))
serial.serialutil.SerialException: Cannot configure port, something went wrong. Original message: PermissionError(13, 'Een apparaat dat op het systeem is aangesloten, werkt niet.', None, 31)
serial.serialutil.SerialException: Cannot configure port, something went wrong. Original message: PermissionError(13, 'Een apparaat dat op het systeem is aangesloten, werkt niet.', None, 31)

I get this message. I don't know whats wrong, please help

**Comment by Mursina** [comment]
I have corrected by just changing the port. I have already connected the esp8266 with COM16 and got the error. Now the code works fine with the port COM 17.

**Comment by SERIDJ** [comment]
hi, i have the same problem, bcs i changed by error driver of  "Dual RS232-HS (Interface 1 ) " from “FTDIBUS (vxxxx)” To usber (v1.0.0.0) and i dont know how i can come back or reset this driver bcs i can flash esp32 again ...

iam using : The ESP-WROVER-KIT with multi-protocol USB bridge (the FTDI FT2232HL)


![image](https://user-images.githubusercontent.com/46067255/81705262-23230600-946f-11ea-90f1-3003cb20af38.png)

![image](https://user-images.githubusercontent.com/46067255/81705181-0b4b8200-946f-11ea-901e-eb031fef3774.png)

![image](https://user-images.githubusercontent.com/46067255/81705322-37670300-946f-11ea-91cf-44af46ff98ee.png)

**Comment by p51pro** [comment]
faced the same problem when I was trying to upload code into the node MCU... the problem in my case was that I was trying to power large motors drivers with common vin, hence I cut the common vin and attached the motor driver separately with an external source. the reason this happens in my case was that i tried to power a large device with a small power source(i.e from my laptop) hence the laptops USB port automatically cuts the power hence it interrupts the uploading process.  
hope this was helpful

**Comment by gramygoal** [comment]
> 发生异常:
> traceback.format_exc():
> Traceback (most recent call last):
> File "D:\xuxu\GPIB_ATUO\at_cmd.py", line 109, in write
> self.ser.open()
> File "C:\Python36-32\lib\site-packages\serial\serialwin32.py", line 78, in open
> self._reconfigure_port()
> File "C:\Python36-32\lib\site-packages\serial\serialwin32.py", line 222, in _reconfigure_port
> 'Original message: {!r}'.format(ctypes.WinError()))
> serial.serialutil.SerialException: Cannot configure port, something went wrong. Original message: PermissionError(13, '连到系统上的设备没有发挥作用。', None, 31)

Have you solved this problem?

**Comment by evloebenstein** [comment]
I get the same error 
i tried to search how to fix the error but i couldn't find anything
please help.

**Comment by azzopardim** [comment]
Thanks this also solved my issue. Disconnected component from the 5V port and it worked

**Comment by GljTest** [comment]
When I run the AT test script, an exception is thrown when opening the AT serial port: could no open port: "PermissionError(13, 'The device connected to the system is not functioning.', None, 31)" I get this message. I don't know whats wrong, please help！

Below is my code ：
try:
    self.controller = serial.Serial(self.com, self.rate)
    # self.log('[%s]open_serial...' % self.module_name)
    rev_threa = threading.Thread(target=self.receive_msg_from_port_thread_py3)
    rev_threa.setDaemon(True)
    self.log('open serial')
    rev_threa.start()
except Exception as ex:
    self.log("SUMMARY:SUB SERVICE:%s,%s" % ("NA", "AT Port Exception"))
    self.log('[%s]serial_open [%s, %d], ERROR:%s' % (self.module_name, self.com, int(self.rate), str(ex)))

**Comment by BAOTT569** [comment]
không biết những tôi đã chuyển Debug Port trong phần Tool thành Serial thì mọi thứ đều bình thường lại

**Comment by sdip2020** [comment]
> Hello there! The package you provided is very useful, but when I was using it recently, the serial port was always broken. The error message is as follows: **serial.serialutil.SerialException: Cannot configure port, something went wrong. Original message: PermissionError(13, 'The device connected to the system is not working.', None, 31)** Those who hope to encounter similar problems can give a solution that has been debugged for a long time! Th

> Hello there! The package you provided is very useful, but when I was using it recently, the serial port was always broken. The error message is as follows: **serial.serialutil.SerialException: Cannot configure port, something went wrong. Original message: PermissionError(13, 'The device connected to the system is not working.', None, 31)** Those who hope to encounter similar problems can give a solution that has been debugged for a long time! Thank you

try instaling CH340G. this help you to communicate with with the bored. the problem you have is pc is not able to give the data to the bored.

**Comment by EWRC01** [comment]
# Possible Solution

Try to uninstall and install again the driver CH34X.

Here is the url [Link to driver download](https://sparks.gogo.co.nz/ch340.html) follow the instructions:

![image](https://github.com/dzhu/myo-raw/assets/71530966/094270c7-1d31-4bf9-a84a-a24912693671)

And works fine, currently i use Windows 11 but in the page are steps to MacOS and Linux.

**Comment by luoies** [comment]
He solucionado el problema, a mi me funciono fue desintalar el driver CH341 original que windows 11 tenia, y volver a instalar el driver de la pagina [https://parzibyte.me/blog/2020/02/09/instalar-driver-esp8266-windows/](url)

**Comment by zhouyibetter** [comment]
After uploading,I received this message.
A serial exception error occurred: Cannot configure port, something went wrong. Original message: PermissionError(13, '����ϵͳ�ϵ��豸û�з������á�', None, 31)
Note: This error originates from pySerial. It is likely not a problem with esptool, but with the hardware connection or drivers.

**Comment by SuperRightHand** [comment]
> # Possible Solution
> Try to uninstall and install again the driver CH34X.
> 
> Here is the url [Link to driver download](https://sparks.gogo.co.nz/ch340.html) follow the instructions:
> 
> ![image](https://user-images.githubusercontent.com/71530966/238728029-094270c7-1d31-4bf9-a84a-a24912693671.png)
> 
> And works fine, currently i use Windows 11 but in the page are steps to MacOS and Linux.

Thanks bro, this is good
